//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Parking_Lot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public long ID { get; set; }
        public string DisplayName { get; set; }
        public string LicensePlate { get; set; }
        public string PhoneNumber { get; set; }
    }
}
