//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Parking_Lot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int ID { get; set; }
        public Nullable<int> SumAvail { get; set; }
    
        public virtual BuildingInfo BuildingInfo { get; set; }
    }
}
