//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_Parking_Lot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarParkingLayout
    {
        public int ID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<System.DateTime> ReservedTime { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual BuildingInfo BuildingInfo { get; set; }
        public virtual PositionStatu PositionStatu { get; set; }
        public virtual User User { get; set; }
    }
}
